#!/usr/bin/env python3
# AutoMSP Document Pipeline
# After any document is created:
# 1. Generate PDF
# 2. Send email via Gmail with PDF attached
# 3. Create/update HubSpot contact + deal + note
# Usage: python3 /root/clawd/send_document.py --pdf /path/to/file.pdf --client-name "Name" --client-email "email" --doc-type "invoice"

import argparse, requests, json, base64, os
from datetime import datetime

HUBSPOT_TOKEN = os.environ.get("HUBSPOT_TOKEN", "")  # Set via environment variable
GMAIL_CREDENTIALS = "/root/.openclaw/gmail_creds.json"

def create_hubspot_contact(name, email, company):
    parts = name.split(' ', 1)
    firstname = parts[0]
    lastname = parts[1] if len(parts) > 1 else ''
    
    resp = requests.post(
        "https://api.hubapi.com/crm/v3/objects/contacts",
        headers={"Authorization": f"Bearer {HUBSPOT_TOKEN}", "Content-Type": "application/json"},
        json={"properties": {
            "firstname": firstname,
            "lastname": lastname,
            "email": email,
            "company": company,
            "lifecyclestage": "lead",
            "hubspot_owner_id": "1609866719"
        }}
    )
    if resp.status_code in (200, 201):
        return resp.json()['id']
    # Check if exists
    search = requests.post(
        "https://api.hubapi.com/crm/v3/objects/contacts/search",
        headers={"Authorization": f"Bearer {HUBSPOT_TOKEN}", "Content-Type": "application/json"},
        json={"filterGroups": [{"filters": [{"propertyName": "email", "operator": "EQ", "value": email}]}]}
    )
    if search.json().get('total', 0) > 0:
        return search.json()['results'][0]['id']
    return None

def create_hubspot_deal(contact_id, company, doc_type, amount):
    resp = requests.post(
        "https://api.hubapi.com/crm/v3/objects/deals",
        headers={"Authorization": f"Bearer {HUBSPOT_TOKEN}", "Content-Type": "application/json"},
        json={"properties": {
            "dealname": f"{company} — AI Automation ({doc_type.title()})",
            "dealstage": "presentationscheduled",
            "amount": str(amount),
            "closedate": datetime.now().strftime("%Y-%m-%d"),
            "hubspot_owner_id": "1609866719",
            "pipeline": "default"
        }}
    )
    if resp.status_code in (200, 201):
        deal_id = resp.json()['id']
        # Associate with contact
        if contact_id:
            requests.put(
                f"https://api.hubapi.com/crm/v3/associations/deals/contacts/batch/create",
                headers={"Authorization": f"Bearer {HUBSPOT_TOKEN}", "Content-Type": "application/json"},
                json={"inputs": [{"from": {"id": deal_id}, "to": {"id": contact_id}, "type": "deal_to_contact"}]}
            )
        return deal_id
    return None

def add_hubspot_note(contact_id, deal_id, doc_type, pdf_path):
    note_body = f"AutoMSP {doc_type.title()} generated on {datetime.now().strftime('%Y-%m-%d %H:%M')} GST\nDocument: {pdf_path}\nGenerated by AutoMSP AI Agent System"
    resp = requests.post(
        "https://api.hubapi.com/crm/v3/objects/notes",
        headers={"Authorization": f"Bearer {HUBSPOT_TOKEN}", "Content-Type": "application/json"},
        json={"properties": {
            "hs_note_body": note_body,
            "hs_timestamp": datetime.now().isoformat() + "Z"
        }}
    )
    if resp.status_code in (200, 201):
        note_id = resp.json()['id']
        for obj_type, obj_id in [("contacts", contact_id), ("deals", deal_id)]:
            if obj_id:
                requests.put(
                    f"https://api.hubapi.com/crm/v3/associations/notes/{obj_type}/batch/create",
                    headers={"Authorization": f"Bearer {HUBSPOT_TOKEN}", "Content-Type": "application/json"},
                    json={"inputs": [{"from": {"id": note_id}, "to": {"id": obj_id}, "type": f"note_to_{obj_type[:-1]}"}]}
                )
        return note_id
    return None

def send_gmail(to_email, to_name, doc_type, pdf_path, company):
    # Use n8n webhook to trigger email send
    N8N_WEBHOOK = "http://192.168.16.8:5678/webhook/send-document"
    
    with open(pdf_path, 'rb') as f:
        pdf_b64 = base64.b64encode(f.read()).decode()
    
    payload = {
        "to_email": to_email,
        "to_name": to_name,
        "doc_type": doc_type,
        "company": company,
        "pdf_filename": os.path.basename(pdf_path),
        "pdf_base64": pdf_b64,
        "from_name": "Moiz Contractor | AutoMSP",
        "from_email": "automspus@gmail.com"
    }
    
    resp = requests.post(N8N_WEBHOOK, json=payload, timeout=30)
    return resp.status_code == 200

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--pdf', required=True)
    parser.add_argument('--client-name', required=True)
    parser.add_argument('--client-email', required=True)
    parser.add_argument('--company', default='')
    parser.add_argument('--doc-type', default='document')
    parser.add_argument('--amount', default='0')
    args = parser.parse_args()
    
    HUBSPOT_TOKEN = os.environ.get('HUBSPOT_TOKEN', '')
    company = args.company or args.client_name
    
    print(f"Processing: {args.doc_type} for {args.client_name}")
    
    # HubSpot
    contact_id = create_hubspot_contact(args.client_name, args.client_email, company)
    print(f"HubSpot contact: {contact_id}")
    
    deal_id = create_hubspot_deal(contact_id, company, args.doc_type, args.amount)
    print(f"HubSpot deal: {deal_id}")
    
    note_id = add_hubspot_note(contact_id, deal_id, args.doc_type, args.pdf)
    print(f"HubSpot note: {note_id}")
    
    # Email
    sent = send_gmail(args.client_email, args.client_name, args.doc_type, args.pdf, company)
    print(f"Email sent: {sent}")
    
    print(f"\nDone! Document pipeline complete for {args.client_name}")
